name: Generate Deploy Notes

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-deploy-notes:
    runs-on: ubuntu-latest
    # Only run if the PR has the 'needs-deploy-note' label or is being merged into main
    if: ${{ github.event.pull_request.base.ref == 'main' && (contains(github.event.pull_request.labels.*.name, 'needs-deploy-note') || github.event.action == 'opened') }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate Deploy Note
        uses: blaze-xyz/deploy-notes-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deepseek-api-key: ${{ secrets.DEEPSEEK_API_KEY }}
          pr-number: ${{ github.event.pull_request.number }}
          repository: ${{ github.repository }} 